//"use client"

import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./app.css";
import { Authenticator } from "@aws-amplify/ui-react";


const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "kotayori",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

   console.log("root layout");

  return (


    <html lang="ja">
    {/* <body className={inter.className}>{children}</body> 
      <Authenticator.Provider> */}
          <body className={inter.className}>{children}</body> 
     {/* </Authenticator.Provider> */}

    </html>
  );
}
